"""Tests for auto-generated shape stubs (Step 99)."""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

import reproducibility.stub_autogen_coverage as harness  # noqa: E402
from src.shape_stub_registry import (  # noqa: E402
    clear_user_stubs,
    get_shape_stub,
)
from src.stub_autogen import (  # noqa: E402
    StubCategory,
    autogenerate_stub,
    classify,
    coverage_report,
    install_autogenerated,
)


def _nn():
    import torch.nn as nn

    return nn


# --- classification --------------------------------------------------------
def test_linear_classified_last_dim_linear():
    nn = _nn()
    assert classify(nn.Linear) is StubCategory.LAST_DIM_LINEAR


def test_relu_classified_shape_preserving():
    nn = _nn()
    assert classify(nn.ReLU) is StubCategory.SHAPE_PRESERVING


def test_conv2d_classified_unsupported():
    nn = _nn()
    assert classify(nn.Conv2d) is StubCategory.UNSUPPORTED


def test_autogen_abstains_on_unsupported():
    nn = _nn()
    assert autogenerate_stub(nn.Conv2d) is None
    assert autogenerate_stub(nn.MaxPool2d) is None


def test_autogen_linear_carries_arg_names():
    nn = _nn()
    stub = autogenerate_stub(nn.Linear)
    assert stub is not None
    assert stub.in_arg == "in_features"
    assert stub.out_arg == "out_features"
    assert "in_features" in stub.arg_names and "out_features" in stub.arg_names


# --- registration ----------------------------------------------------------
def test_install_registers_into_registry():
    clear_user_stubs()
    try:
        installed = install_autogenerated()
        assert "Linear" in installed
        assert "ReLU" in installed
        assert "Conv2d" not in installed  # soundly abstained
        assert get_shape_stub("Linear") is not None
        assert get_shape_stub("ReLU") is not None
        assert get_shape_stub("Conv2d") is None
    finally:
        clear_user_stubs()


def test_coverage_report_counts():
    rep = coverage_report()
    assert rep["n_targets"] == rep["n_stubs_generated"] + rep["n_abstained"]
    assert rep["n_abstained"] >= 1


# --- live validation -------------------------------------------------------
def test_all_generated_stubs_match_live_forward():
    data = harness.measure()
    assert data["all_generated_shapes_match"] is True
    assert data["n_live_checked"] >= 20


def test_abstained_classes_are_expected():
    data = harness.measure()
    assert set(data["abstained_classes"]) >= {"Conv2d", "MaxPool2d"}


def test_thirdparty_layer_autocovered():
    data = harness.measure()
    tp = data["thirdparty"]
    assert tp["stub_generated"] is True
    assert tp["category"] == "last_dim_linear"
    assert tp["shape_match"] is True


def test_linear_stub_predicts_last_dim():
    data = harness.measure()
    lin = next(r for r in data["rows"] if r["class_name"] == "Linear")
    assert lin["predicted_shape"] == lin["live_shape"]
    assert lin["live_shape"][-1] == 5


# --- determinism -----------------------------------------------------------
_VOLATILE_SUBSTRINGS = (
    "time", "elapsed", "timestamp", "wall", "clock",
    "_ms", "seconds", "duration", "date",
)


def _walk_keys(obj):
    if isinstance(obj, dict):
        for k, v in obj.items():
            yield k
            yield from _walk_keys(v)
    elif isinstance(obj, list):
        for v in obj:
            yield from _walk_keys(v)


def test_artifact_has_no_volatile_fields():
    data = harness.measure()
    for key in _walk_keys(data):
        low = key.lower()
        for bad in _VOLATILE_SUBSTRINGS:
            assert bad not in low, f"volatile substring {bad!r} in key {key!r}"


def test_artifact_is_byte_deterministic():
    assert harness.run(check=True) == 0
