"""TensorGuard symbolic-execution / abstract-interpretation engine.

A Python-level symbolic executor that interprets ``nn.Module`` ``__init__`` /
``forward`` and shipped ``__main__`` demos over an abstract domain of tensor
metadata (rank, symbolic shape, dtype) plus Python structural values (tuple
arity, None-ness, containers, integer linear expressions).  It catches
Python-semantics bugs the FX + SMT shape path is blind to — tuple-unpacking
arity, rank-dependent indexing, loop-built layer dims — the bug classes seen in
real open-source repos.

See ``SYMEXEC_100_STEPS.md`` for the full roadmap.
"""

from __future__ import annotations

from .abstain import AbstainCategory, AbstainLedger, AbstainReason
from .coverage import CoverageMeter, StmtCoverage
from .bugs import SymBug, SymBugKind
from .confidence import ConfidenceSignals, MAX_CONFIDENCE, calibrate
from .concretize import (
    ConcreteTensor,
    alpha,
    force_counterexample,
    gamma,
    gamma_samples,
)
from .engine import SymResult, analyze_file, analyze_source, ITERATION_CAPS
from .config import SymConfig, MODES, DEFAULT_CONFIG
from .benchmark import (
    BenchmarkRecord,
    benchmark_paths,
    benchmark_source,
    summarise,
)
from .fuzz import (
    FuzzCrash,
    FuzzReport,
    MutationResult,
    fuzz,
    mutate,
    rename_local,
)
from .explain import Explanation, explain_bug, explain_bugs
from .export import (
    EXPORT_SCHEMA_VERSION,
    SARIF_VERSION,
    bug_to_dict,
    result_to_dict,
    to_sarif,
)
from .integrations import (
    LSP_SOURCE,
    render_github_annotations,
    to_github_annotations,
    to_lsp_diagnostics,
    to_publish_diagnostics,
)
from .notebook import (
    CellFinding,
    NotebookCell,
    NotebookResult,
    analyze_notebook,
    parse_notebook,
)
from .footprint import FOOTPRINT_VERSION, ProofFootprint, bug_fingerprint, footprint
from .bytecode import (
    abstract_to_concrete,
    fold_expr,
    fold_to_abstract,
    safe_eval_code,
)
from .package import (
    ModuleInfo,
    PackageIndex,
    PackageResult,
    analyze_package,
)
from .stubs import STUB_REGISTRY, lookup as stub_lookup
from .incremental import (
    IncrementalCache,
    IncrementalStats,
    UnitChange,
    analyze_package_incremental,
    analyze_source_incremental,
    diff_units,
    unit_index,
)
from .parallel import analyze_package_parallel
from .telemetry import (
    CalibrationRecord,
    CalibrationReport,
    KindStats,
    PriorSuggestion,
    ReliabilityBin,
    TelemetrySink,
    brier_score,
    calibration_report,
    expected_calibration_error,
    precision_by_kind,
    records_from_jsonl,
    records_to_jsonl,
    reliability_table,
    suggest_prior_adjustments,
)
from .mutation_testing import (
    Mutant,
    MutationReport,
    generate_mutants,
    lattice_oracle,
    make_corpus_oracle,
    run_mutation_testing,
    run_pytest_mutation_testing,
)
from .certificate import (
    CERTIFICATE_VERSION,
    PRECONDITIONS,
    BugCertificate,
    certify,
    certify_result,
    certificate_to_dict,
    certificate_from_dict,
    dumps_certificates,
    loads_certificates,
)
from .replay import (
    ReplayResult,
    replay,
    replay_all,
    replay_text,
    all_verified,
)
from .repro import (
    ReproScript,
    ReproResult,
    generate_repro,
    generate_repros,
    confirm,
)
from .autofix import (
    FixCandidate,
    VerifiedFix,
    propose_fix,
    verify_fix,
    repair,
)
from .contracts import (
    TensorSpec,
    ParamContract,
    FunctionContract,
    infer_contracts,
    to_pyi,
    contracts_to_pyi,
)
from .safety import (
    SafetyReport,
    safety_report,
    render_safety_report,
    explain_safety,
)
from .safety_certificate import (
    SafetyObligation,
    SafetyCertificate,
    SafetyVerification,
    certify_safety,
    verify_safety_certificate,
    safety_certificate_to_dict,
    safety_certificate_from_dict,
    dumps_safety_certificate,
    loads_safety_certificate,
    render_safety_certificate,
    certify_file,
    verify_certificate_file,
    LEAN_REFUTATION_FOR,
)
from .weights import (
    WEIGHTS_CERTIFICATE_VERSION,
    WeightTensorInfo,
    WeightsFinding,
    WeightsSafetyCertificate,
    WeightsVerification,
    read_safetensors_header,
    certify_weights_file,
    verify_weights_certificate,
    weights_contract_from_file,
    weights_certificate_to_dict,
    weights_certificate_from_dict,
    dumps_weights_certificate,
    loads_weights_certificate,
    render_weights_certificate,
)
from .model_contract import (
    AbstainCode,
    Abstention,
    CoverageReport,
    ModelContract,
    derive_model_contract,
    model_contract_to_expected,
    certify_weights_against_model,
)
from .interpreter import Interpreter
from .serialize import (
    StateDiff,
    diff_states,
    diff_to_json,
    dumps,
    from_json,
    pretty,
    pretty_diff,
    pretty_state,
    state_from_json,
    state_to_json,
    to_json,
)
from .state import State
from .values import (
    AbstractValue,
    BoolVal,
    DictVal,
    FloatVal,
    IntVal,
    ListVal,
    ModuleVal,
    NoneVal,
    StrVal,
    TensorVal,
    TupleVal,
)

__all__ = [
    "analyze_source",
    "analyze_file",
    "SymResult",
    "ITERATION_CAPS",
    "SymConfig",
    "MODES",
    "DEFAULT_CONFIG",
    "BenchmarkRecord",
    "benchmark_source",
    "benchmark_paths",
    "summarise",
    "MutationResult",
    "mutate",
    "rename_local",
    "FuzzCrash",
    "FuzzReport",
    "fuzz",
    "SymBug",
    "SymBugKind",
    "Interpreter",
    "State",
    "AbstractValue",
    "TensorVal",
    "TupleVal",
    "IntVal",
    "BoolVal",
    "FloatVal",
    "StrVal",
    "ListVal",
    "DictVal",
    "ModuleVal",
    "NoneVal",
    "gamma",
    "gamma_samples",
    "alpha",
    "force_counterexample",
    "ConcreteTensor",
    "pretty",
    "pretty_state",
    "to_json",
    "from_json",
    "state_to_json",
    "state_from_json",
    "dumps",
    "StateDiff",
    "diff_states",
    "pretty_diff",
    "diff_to_json",
    "AbstainCategory",
    "AbstainReason",
    "AbstainLedger",
    "CoverageMeter",
    "StmtCoverage",
    "FOOTPRINT_VERSION",
    "ProofFootprint",
    "bug_fingerprint",
    "footprint",
    "fold_expr",
    "fold_to_abstract",
    "abstract_to_concrete",
    "safe_eval_code",
    "ModuleInfo",
    "PackageIndex",
    "PackageResult",
    "analyze_package",
    "STUB_REGISTRY",
    "stub_lookup",
    "IncrementalCache",
    "IncrementalStats",
    "UnitChange",
    "analyze_package_incremental",
    "analyze_source_incremental",
    "diff_units",
    "unit_index",
    "analyze_package_parallel",
    "CalibrationRecord",
    "CalibrationReport",
    "KindStats",
    "PriorSuggestion",
    "ReliabilityBin",
    "TelemetrySink",
    "brier_score",
    "calibration_report",
    "expected_calibration_error",
    "precision_by_kind",
    "records_from_jsonl",
    "records_to_jsonl",
    "reliability_table",
    "suggest_prior_adjustments",
    "Mutant",
    "MutationReport",
    "generate_mutants",
    "lattice_oracle",
    "make_corpus_oracle",
    "run_mutation_testing",
    "run_pytest_mutation_testing",
    "ConfidenceSignals",
    "MAX_CONFIDENCE",
    "calibrate",
    "Explanation",
    "explain_bug",
    "explain_bugs",
    "EXPORT_SCHEMA_VERSION",
    "SARIF_VERSION",
    "bug_to_dict",
    "result_to_dict",
    "to_sarif",
    "LSP_SOURCE",
    "to_lsp_diagnostics",
    "to_publish_diagnostics",
    "to_github_annotations",
    "CellFinding",
    "NotebookCell",
    "NotebookResult",
    "analyze_notebook",
    "parse_notebook",
    "render_github_annotations",
    "CERTIFICATE_VERSION",
    "PRECONDITIONS",
    "BugCertificate",
    "certify",
    "certify_result",
    "certificate_to_dict",
    "certificate_from_dict",
    "dumps_certificates",
    "loads_certificates",
    "ReplayResult",
    "replay",
    "replay_all",
    "replay_text",
    "all_verified",
    "ReproScript",
    "ReproResult",
    "generate_repro",
    "generate_repros",
    "confirm",
    "FixCandidate",
    "VerifiedFix",
    "propose_fix",
    "verify_fix",
    "repair",
    "TensorSpec",
    "ParamContract",
    "FunctionContract",
    "infer_contracts",
    "to_pyi",
    "contracts_to_pyi",
    "SafetyReport",
    "safety_report",
    "render_safety_report",
    "explain_safety",
    "SafetyObligation",
    "SafetyCertificate",
    "SafetyVerification",
    "certify_safety",
    "verify_safety_certificate",
    "safety_certificate_to_dict",
    "safety_certificate_from_dict",
    "dumps_safety_certificate",
    "loads_safety_certificate",
    "render_safety_certificate",
    "certify_file",
    "verify_certificate_file",
    "LEAN_REFUTATION_FOR",
    "WEIGHTS_CERTIFICATE_VERSION",
    "WeightTensorInfo",
    "WeightsFinding",
    "WeightsSafetyCertificate",
    "WeightsVerification",
    "read_safetensors_header",
    "certify_weights_file",
    "verify_weights_certificate",
    "weights_contract_from_file",
    "weights_certificate_to_dict",
    "weights_certificate_from_dict",
    "dumps_weights_certificate",
    "loads_weights_certificate",
    "render_weights_certificate",
    "ModelContract",
    "AbstainCode",
    "Abstention",
    "CoverageReport",
    "derive_model_contract",
    "model_contract_to_expected",
    "certify_weights_against_model",
]
