"""Auto-generated by reproducibility/dynamo_falsifier_curated_corpus.py.

Five custom-op-bearing nn.Module fixtures whose Dynamo guard kind
is != INT and lives outside catalogue(M).
"""
import torch
import torch.nn as nn

@torch.library.custom_op('repro::shape_branch_last', mutates_args=())
def _shape_branch_last(x: torch.Tensor) -> torch.Tensor:
    return x * 1.0 if (x.shape[-1] % 2 == 0) else x + 1.0
@_shape_branch_last.register_fake
def _f1(x): return torch.empty_like(x)

@torch.library.custom_op('repro::rank_branch', mutates_args=())
def _rank_branch(x: torch.Tensor) -> torch.Tensor:
    return x * 2.0 if x.dim() == 3 else x + 2.0
@_rank_branch.register_fake
def _f2(x): return torch.empty_like(x)

@torch.library.custom_op('repro::dtype_branch', mutates_args=())
def _dtype_branch(x: torch.Tensor) -> torch.Tensor:
    return x * 0.5 if x.dtype == torch.float32 else x + 0.5
@_dtype_branch.register_fake
def _f3(x): return torch.empty_like(x)

@torch.library.custom_op('repro::interior_branch', mutates_args=())
def _interior_branch(x: torch.Tensor) -> torch.Tensor:
    return x + 1.0 if x.shape[1] > 4 else x - 1.0
@_interior_branch.register_fake
def _f4(x): return torch.empty_like(x)

@torch.library.custom_op('repro::numel_branch', mutates_args=())
def _numel_branch(x: torch.Tensor) -> torch.Tensor:
    return x * 1.5 if x.numel() % 7 == 0 else x - 1.5
@_numel_branch.register_fake
def _f5(x): return torch.empty_like(x)


class ShapeGuardModule(nn.Module):
    def __init__(self, dim_in, dim_out):
        super().__init__()
        self.linear = nn.Linear(dim_in, dim_out)
    def forward(self, x):
        return torch.ops.repro.shape_branch_last(self.linear(x))


class RankGuardModule(nn.Module):
    def __init__(self, dim_in, dim_out):
        super().__init__()
        self.proj = nn.Linear(dim_in, dim_out)
    def forward(self, x):
        return torch.ops.repro.rank_branch(self.proj(x))


class DtypeGuardModule(nn.Module):
    def __init__(self, dim_in, dim_out):
        super().__init__()
        self.lin = nn.Linear(dim_in, dim_out)
    def forward(self, x):
        return torch.ops.repro.dtype_branch(self.lin(x))


class InteriorShapeGuardModule(nn.Module):
    def __init__(self, dim_in, dim_out):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(dim_out, dim_in))
    def forward(self, x):
        return torch.ops.repro.interior_branch(x @ self.weight.T)


class ProductShapeGuardModule(nn.Module):
    def __init__(self, dim_in, dim_out):
        super().__init__()
        self.proj = nn.Linear(dim_in, dim_out)
    def forward(self, x):
        return torch.ops.repro.numel_branch(self.proj(x))
