"""Auto-generate shape stubs from real ``torch.nn`` signatures (Step 99).

The manual :mod:`src.shape_stub_registry` lets a user *hand-write* a shape
transfer for a third-party layer.  That does not scale: PyTorch ships hundreds
of layers and the ecosystem adds thousands more.  This module closes the gap by
**deriving** shape stubs automatically from the real constructor signatures and
known shape contracts of ``torch.nn`` classes, so coverage can grow with one
curated list instead of one hand-written transfer per layer.

Crucially, autogeneration is *sound by abstention*: we only emit a stub when the
layer falls into a category whose shape contract is exactly known
(:class:`StubCategory`).  Anything else (e.g. convolutions, whose output spatial
dims depend on stride/padding/dilation) is classified ``UNSUPPORTED`` and **no**
stub is produced — TensorGuard then treats the layer opaquely rather than
guessing.  Every generated stub is validated against the *live* layer's forward
in ``reproducibility/stub_autogen_coverage.py``.

Public API
----------
``classify(cls) -> StubCategory``
``autogenerate_stub(cls) -> Optional[AutoStub]``
``install_autogenerated(classes=None) -> list[str]``  (registers into the
    shared shape-stub registry; returns the names installed)
``DEFAULT_TARGETS`` — curated list of ``torch.nn`` class names to cover.
"""

from __future__ import annotations

import inspect
from dataclasses import dataclass
from enum import Enum
from typing import List, Optional, Sequence

from src.shape_stub_registry import (
    register_last_dim_linear,
    register_shape_preserving,
)


class StubCategory(Enum):
    """Shape-contract category a layer was classified into."""

    LAST_DIM_LINEAR = "last_dim_linear"
    SHAPE_PRESERVING = "shape_preserving"
    UNSUPPORTED = "unsupported"


# Layers whose output shape equals the input shape for every valid input.
# (Elementwise activations, dropout, and normalization layers that do not
# change rank or any dimension.)  Curated and validated against live torch.
_SHAPE_PRESERVING_NAMES = frozenset(
    {
        "ReLU",
        "ReLU6",
        "GELU",
        "SiLU",
        "Mish",
        "Sigmoid",
        "Tanh",
        "ELU",
        "CELU",
        "SELU",
        "LeakyReLU",
        "Hardswish",
        "Hardsigmoid",
        "Hardtanh",
        "Softplus",
        "Softsign",
        "Softmax",
        "LogSoftmax",
        "Dropout",
        "Dropout1d",
        "Dropout2d",
        "Dropout3d",
        "AlphaDropout",
        "LayerNorm",
        "RMSNorm",
        "BatchNorm1d",
        "BatchNorm2d",
        "BatchNorm3d",
        "GroupNorm",
        "InstanceNorm1d",
        "InstanceNorm2d",
        "InstanceNorm3d",
        "Identity",
    }
)


@dataclass(frozen=True)
class AutoStub:
    """An auto-derived stub description for a layer class."""

    class_name: str
    category: StubCategory
    # for LAST_DIM_LINEAR: the constructor arg names carrying in/out features
    in_arg: Optional[str] = None
    out_arg: Optional[str] = None
    # positional constructor argument order (for mapping source-call args)
    arg_names: tuple = ()

    def to_dict(self) -> dict:
        return {
            "class_name": self.class_name,
            "category": self.category.value,
            "in_arg": self.in_arg,
            "out_arg": self.out_arg,
            "arg_names": list(self.arg_names),
        }


def _init_params(cls) -> List[str]:
    try:
        params = list(inspect.signature(cls.__init__).parameters)
    except (ValueError, TypeError):
        return []
    # drop ``self``
    return [p for p in params if p != "self"]


def _class_name(cls) -> str:
    return getattr(cls, "__name__", str(cls))


def classify(cls) -> StubCategory:
    """Classify *cls* into a shape-contract category from its real signature."""
    name = _class_name(cls)
    params = set(_init_params(cls))

    # Linear-like: a constructor exposing both an input- and output-feature arg.
    if {"in_features", "out_features"} <= params:
        return StubCategory.LAST_DIM_LINEAR

    if name in _SHAPE_PRESERVING_NAMES:
        return StubCategory.SHAPE_PRESERVING

    return StubCategory.UNSUPPORTED


def autogenerate_stub(cls) -> Optional[AutoStub]:
    """Derive an :class:`AutoStub` for *cls*, or ``None`` if unsupported.

    Sound by abstention: returns ``None`` whenever the shape contract is not
    exactly known, so no incorrect stub is ever produced.
    """
    cat = classify(cls)
    name = _class_name(cls)
    if cat is StubCategory.LAST_DIM_LINEAR:
        return AutoStub(
            class_name=name,
            category=cat,
            in_arg="in_features",
            out_arg="out_features",
            arg_names=tuple(_init_params(cls)),
        )
    if cat is StubCategory.SHAPE_PRESERVING:
        return AutoStub(class_name=name, category=cat)
    return None


# Curated set of torch.nn classes to auto-cover. These are layers with stable,
# widely-used shape contracts; the list is intentionally conservative.
DEFAULT_TARGETS = (
    "Linear",
    "ReLU",
    "ReLU6",
    "GELU",
    "SiLU",
    "Mish",
    "Sigmoid",
    "Tanh",
    "ELU",
    "LeakyReLU",
    "Hardswish",
    "Softmax",
    "LogSoftmax",
    "Dropout",
    "Dropout2d",
    "AlphaDropout",
    "LayerNorm",
    "RMSNorm",
    "BatchNorm1d",
    "BatchNorm2d",
    "GroupNorm",
    "InstanceNorm2d",
    "Identity",
    # deliberately included to demonstrate sound abstention (UNSUPPORTED):
    "Conv2d",
    "MultiheadAttention",
    "MaxPool2d",
)


def _resolve_targets(classes: Optional[Sequence]) -> List:
    if classes is not None:
        return list(classes)
    import torch.nn as nn

    resolved = []
    for nm in DEFAULT_TARGETS:
        cls = getattr(nn, nm, None)
        if cls is not None:
            resolved.append(cls)
    return resolved


def install_autogenerated(classes: Optional[Sequence] = None) -> List[str]:
    """Auto-generate and register stubs into the shared shape-stub registry.

    Returns the list of class names for which a stub was installed (UNSUPPORTED
    layers are skipped). Idempotent: re-registering the same name is a no-op
    overwrite in the registry.
    """
    installed: List[str] = []
    for cls in _resolve_targets(classes):
        stub = autogenerate_stub(cls)
        if stub is None:
            continue
        if stub.category is StubCategory.LAST_DIM_LINEAR:
            register_last_dim_linear(
                stub.class_name,
                in_arg=stub.in_arg,
                out_arg=stub.out_arg,
                arg_names=stub.arg_names,
            )
        elif stub.category is StubCategory.SHAPE_PRESERVING:
            register_shape_preserving(stub.class_name)
        installed.append(stub.class_name)
    return installed


def coverage_report(classes: Optional[Sequence] = None) -> dict:
    """Summarize how the target classes were classified (no registration)."""
    rows = []
    for cls in _resolve_targets(classes):
        stub = autogenerate_stub(cls)
        rows.append(
            {
                "class_name": _class_name(cls),
                "category": classify(cls).value,
                "stub_generated": stub is not None,
            }
        )
    rows.sort(key=lambda r: r["class_name"])
    n_gen = sum(1 for r in rows if r["stub_generated"])
    return {
        "rows": rows,
        "n_targets": len(rows),
        "n_stubs_generated": n_gen,
        "n_abstained": len(rows) - n_gen,
    }
