"""PyTorch lifecycle gates exposed as ``tensorguard.torch``."""

from __future__ import annotations

from src.torch_integration import (
    AOTPackageGateResult,
    AOTPackageIssue,
    ONNXExportGateResult,
    ONNXExportIssue,
    ONNXLoweredOp,
    ONNXShapeRoundTripCheck,
    TensorGuardAOTPackageError,
    TensorGuardDynamicShapeError,
    TensorGuardONNXExportError,
    TensorGuardONNXShapeInferenceError,
    TensorGuardViolation,
    guarded_aot_package,
    guarded_compile,
    guarded_onnx_export,
    make_tensorguard_backend,
    verify_onnx_export_contract,
    verify_aot_package_contract,
    verify_exported_program,
    verify_module,
)
from src.gguf_export import (
    GGUFExportGateResult,
    GGUFExportIssue,
    GGUFTensorInfo,
    TensorGuardGGUFExportError,
    guarded_gguf_export,
    verify_gguf_export_contract,
)
from src.optimizer_state_verify import (
    OptimizerStateIssue,
    OptimizerStateShard,
    OptimizerStateVerificationResult,
    TensorGuardOptimizerStateError,
    guarded_optimizer_load_state_dict,
    verify_optimizer_state,
)
from src.checkpoint_verify import (
    CheckpointIssue,
    CheckpointVerificationResult,
    TensorGuardCheckpointError,
    TensorParallelCheckpointShard,
    guarded_load_state_dict,
    verify_checkpoint_state_dict,
)
from src.lora_verification import (
    LoRACompatibilityIssue,
    LoRACompatibilityResult,
    verify_lora_adapter_compatibility,
    verify_lora_model,
)
from src.serving_schema import (
    ServingSchemaGateResult,
    ServingSchemaIssue,
    ServingTensorSpec,
    TensorGuardServingSchemaError,
    guarded_fastapi_endpoint,
    guarded_model_serving_call,
    guarded_torchserve_handler,
    verify_serving_schema,
)
from src.cuda_graph_capture import (
    CudaGraphCaptureEligibilityResult,
    CudaGraphCaptureIssue,
    CudaGraphInputSignature,
    TensorGuardCudaGraphCaptureError,
    guarded_cuda_graph_capture,
    verify_cuda_graph_capture_eligibility,
)

__all__ = [
    "AOTPackageGateResult",
    "AOTPackageIssue",
    "GGUFExportGateResult",
    "GGUFExportIssue",
    "GGUFTensorInfo",
    "ONNXExportGateResult",
    "ONNXExportIssue",
    "ONNXLoweredOp",
    "ONNXShapeRoundTripCheck",
    "TensorGuardAOTPackageError",
    "TensorGuardDynamicShapeError",
    "TensorGuardGGUFExportError",
    "TensorGuardCheckpointError",
    "TensorGuardOptimizerStateError",
    "TensorGuardONNXExportError",
    "TensorGuardONNXShapeInferenceError",
    "TensorGuardServingSchemaError",
    "TensorGuardCudaGraphCaptureError",
    "TensorGuardViolation",
    "guarded_aot_package",
    "guarded_compile",
    "guarded_gguf_export",
    "guarded_load_state_dict",
    "guarded_model_serving_call",
    "guarded_optimizer_load_state_dict",
    "guarded_onnx_export",
    "guarded_fastapi_endpoint",
    "guarded_torchserve_handler",
    "guarded_cuda_graph_capture",
    "make_tensorguard_backend",
    "verify_onnx_export_contract",
    "verify_aot_package_contract",
    "verify_exported_program",
    "verify_gguf_export_contract",
    "verify_checkpoint_state_dict",
    "verify_lora_adapter_compatibility",
    "verify_lora_model",
    "verify_optimizer_state",
    "verify_serving_schema",
    "verify_cuda_graph_capture_eligibility",
    "verify_module",
    "OptimizerStateIssue",
    "OptimizerStateShard",
    "OptimizerStateVerificationResult",
    "CheckpointIssue",
    "CheckpointVerificationResult",
    "TensorParallelCheckpointShard",
    "LoRACompatibilityIssue",
    "LoRACompatibilityResult",
    "ServingSchemaGateResult",
    "ServingSchemaIssue",
    "ServingTensorSpec",
    "CudaGraphCaptureEligibilityResult",
    "CudaGraphCaptureIssue",
    "CudaGraphInputSignature",
]
